services:
  - type: web
    name: payment-retry-api
    env: python
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free
